bootstrap.memory_lock: false
cluster.name: elasticsearch
http.port: 9200
# 2023-08-05
# "How did I fix «Fielddata access on the _id field is disallowed» in Magento 2.4.7-beta1 and Elasticsearch 8?":
# https://mage2.pro/t/6377
indices.id_field_data.enabled: true
node.roles: ["data", "ingest", "master"]
node.name: DMITRII
path.data: E:\server\elasticsearch\data
path.logs: C:\server\log\elasticsearch
transport.port: 9300
xpack.license.self_generated.type: basic
xpack.security.enabled: false
